### PR TITLE
Add a general Djot benchmark for Haskell, JavaScript, and Rust.

### PR DESCRIPTION
**Pull request by dcampbell24**
Partially implements #7.

### CODE REVIEW

**Comment by dcampbell24** [comment]
Why is it failing when it is not trying to build `bench/general`:
```
Run cargo build -p jotdown
    Updating crates.io index
error: failed to select a version for the requirement `reqwest = "=0.12.9"`
candidate versions found which didn't match: 0.11.23, 0.11.22, 0.11.21, ...
location searched: crates.io index
required by package `bench-general v0.1.0 (/home/runner/work/jotdown/jotdown/bench/general)`
Error: Process completed with exit code 101.

 cargo test -p test-html-ut
    Updating crates.io index
error: failed to select a version for the requirement `reqwest = "=0.12.9"`
candidate versions found which didn't match: 0.11.23, 0.11.22, 0.11.21, ...
location searched: crates.io index
required by package `bench-general v0.1.0 (/home/runner/work/jotdown/jotdown/bench/general)`
make: *** [Makefile:32: test_html_ut] Error 101
Error: Process completed with exit code 2.
```

**Comment by hellux** [comment]
> Why is it failing when it is not trying to build `bench/general`:

Cargo seems to try to resolve all dependencies in the whole workspace regardless of what crate is being built. Seems like there is a problem with building this crate on 1.56, causing it to fail on the two 1.56 steps. This crate doesnt have to be compatible with 1.56 so might be better to exclude it from the main workspace and let it become standalone.

Since this benchmark is only testing implementations via separate commands, there might not be much of a benefit to use Rust here. Also, it currently only performs a single run for each implementation, it might be better to use a benchmarking tool, e.g. something like [hyperfine](https://github.com/sharkdp/hyperfine) to get a better statistical result. So I'm thinking that this could be solved with e.g. a simple Makefile or shell script that uses curl to fetch the input and hyperfine to perform the benchmark and maybe produce some plot.

Also, to get the most benefit of this, it would be useful if the whole process was automated, including the retrieval of the implementations. This would allow us to run it in the CI job to make sure it doesnt break, and make it easier for anyone to quickly run on their machine. In that case it might be easier to fetch their repositories and compile them (in release mode), e.g. similar to how it is done for the html-ref tests which runs the reference implementation from a submodule in ext/djot.js.

Also, this is quite independent of jotdown, it could potentially reside in a completely separate repo. Maintaining it independently rather than here might also give it more credibility to not be biased toward this specific implementation.

**Comment by dcampbell24** [comment]
Okay, I made a pull request against [djot](https://github.com/jgm/djot/pull/325). It is currently WIP, and I don't know how you test CI. When I figure out how to test, I can update to grab the repositories instead of the `bin`. I will look more into how `html-ref` is doing things. (I used `wget` instead of `curl`, because `curl` was grabbing an empty file.)

**Comment by dcampbell24** [comment]
I figured out how to test CI setups.

**Comment by dcampbell24** [comment]
I going to close this as discussion can continue in https://github.com/jgm/djot/pull/326.

**Pull request closed without merging**
