### PR TITLE
criterion/iai benchmarks

### PR DESCRIPTION
**Pull request by hellux**
Addresses #2 

Add make rule to generate benchmarks. Generate with `make bench`, can then be run with e.g.

```
cargo bench -- readme
```

djot files are borrowed from jgm/djot.js/bench. there are three groups of benchmarks:

- block: block parse only,
- parse: block parse + inline parse,
- html: block parse + inline parse + write html

example from my machine on current master:

```
block_block_bq_flat             [1.0765 µs 1.0787 µs 1.0810 µs]
block_block_bq_nested           [3.8039 µs 3.8058 µs 3.8078 µs]
block_block_code                [741.68 ns 744.41 ns 746.67 ns]
block_block_fences              [783.88 ns 785.64 ns 787.72 ns]
block_block_heading             [3.3153 µs 3.3183 µs 3.3210 µs]
block_block_hr                  [701.92 ns 703.72 ns 705.17 ns]
block_block_list_flat           [7.6772 µs 7.6793 µs 7.6815 µs]
block_block_list_nested         [7.0689 µs 7.0705 µs 7.0719 µs]
block_block_ref_flat            [1.5536 µs 1.5553 µs 1.5566 µs]
block_block_ref_nested          [982.09 ns 984.48 ns 986.62 ns]
block_inline_autolink           [1.5647 µs 1.5683 µs 1.5717 µs]
block_inline_backticks          [499.77 ns 499.98 ns 500.17 ns]
block_inline_em_flat            [673.68 ns 677.70 ns 681.73 ns]
block_inline_em_nested          [657.32 ns 660.46 ns 663.69 ns]
block_inline_em_worst           [726.76 ns 729.21 ns 731.34 ns]
block_inline_escape             [935.58 ns 937.40 ns 938.89 ns]
block_inline_links_flat         [1.9214 µs 1.9220 µs 1.9226 µs]
block_inline_links_nested       [1.3016 µs 1.3046 µs 1.3077 µs]
block_lorem1                    [4.7890 µs 4.7900 µs 4.7910 µs]
block_readme                    [43.461 µs 43.465 µs 43.469 µs]

parse_block_bq_flat             [4.8407 µs 4.8423 µs 4.8437 µs]
parse_block_bq_nested           [8.7305 µs 8.7342 µs 8.7377 µs]
parse_block_code                [818.25 ns 819.82 ns 821.20 ns]
parse_block_fences              [875.38 ns 877.18 ns 878.73 ns]
parse_block_heading             [5.8719 µs 5.8744 µs 5.8767 µs]
parse_block_hr                  [2.6148 µs 2.6161 µs 2.6174 µs]
parse_block_list_flat           [16.959 µs 16.962 µs 16.965 µs]
parse_block_list_nested         [13.267 µs 13.271 µs 13.275 µs]
parse_block_ref_flat            [10.394 µs 10.400 µs 10.407 µs]
parse_block_ref_nested          [11.999 µs 12.002 µs 12.005 µs]
parse_inline_autolink           [10.117 µs 10.120 µs 10.123 µs]
parse_inline_backticks          [1.7603 µs 1.7610 µs 1.7618 µs]
parse_inline_em_flat            [4.7761 µs 4.7800 µs 4.7834 µs]
parse_inline_em_nested          [4.5629 µs 4.5649 µs 4.5670 µs]
parse_inline_em_worst           [5.7709 µs 5.7730 µs 5.7752 µs]
parse_inline_escape             [6.0860 µs 6.0890 µs 6.0917 µs]
parse_inline_links_flat         [12.505 µs 12.508 µs 12.511 µs]
parse_inline_links_nested       [14.132 µs 14.136 µs 14.141 µs]
parse_lorem1                    [54.697 µs 54.721 µs 54.744 µs]
parse_readme                    [201.21 µs 201.24 µs 201.27 µs]

html_block_bq_flat              [5.1938 µs 5.1972 µs 5.2006 µs]
html_block_bq_nested            [9.3844 µs 9.3906 µs 9.3959 µs]
html_block_code                 [1.0169 µs 1.0195 µs 1.0220 µs]
html_block_fences               [1.0297 µs 1.0324 µs 1.0349 µs]
html_block_heading              [6.6186 µs 6.6200 µs 6.6213 µs]
html_block_hr                   [2.7527 µs 2.7549 µs 2.7570 µs]
html_block_list_flat            [18.802 µs 18.805 µs 18.809 µs]
html_block_list_nested          [14.975 µs 14.981 µs 14.987 µs]
html_block_ref_flat             [11.596 µs 11.603 µs 11.611 µs]
html_block_ref_nested           [12.470 µs 12.474 µs 12.479 µs]
html_inline_autolink            [11.321 µs 11.325 µs 11.329 µs]
html_inline_backticks           [2.0611 µs 2.0621 µs 2.0630 µs]
html_inline_em_flat             [5.2366 µs 5.2384 µs 5.2402 µs]
html_inline_em_nested           [5.1373 µs 5.1395 µs 5.1418 µs]
html_inline_em_worst            [6.1175 µs 6.1204 µs 6.1236 µs]
html_inline_escape              [6.5492 µs 6.5522 µs 6.5550 µs]
html_inline_links_flat          [13.700 µs 13.703 µs 13.707 µs]
html_inline_links_nested        [15.028 µs 15.032 µs 15.035 µs]
html_lorem1                     [57.899 µs 57.914 µs 57.932 µs]
html_readme                     [223.90 µs 223.94 µs 223.97 µs]
```

seems to be approximately 20% block parse, 70% inline parse, and 10% html output.

### CODE REVIEW

**Comment by kmaasrud** [comment]
> seems to be approximately 20% block parse, 70% inline parse, and 10% html output.

Would it be useful to automate finding those ratios? Also perhaps a bigger test or even the cumulative sum of all these benches would be interesting? Just spitballing

**Comment by hellux** [comment]
> > seems to be approximately 20% block parse, 70% inline parse, and 10%
> > html output.
>
> Would it be useful to automate finding those ratios?

Criterion should hopefully have some easily parsable output format we
can use to do some simple aggregation/analysis on the results.

> Also perhaps a bigger test or even the cumulative sum of all these
> benches would be interesting? Just spitballing

Adding specific manual tests is easy: just add a .dj file in the benches
directory and it will be used to generate benchmarks. If we want a large
test it might be best to generate it and avoid checking it into the
repo, though.

Cumulative sum could perhaps be useful to estimate an overall impact of
a change, but then all benchmarks would be weighted equally. Which is
not necessarily ideal, some might for example test obscure edge cases.

Skimming through the criterion user guide, there is at least a
throughput feature which should let one achieve some form of
normalization between the inputs. Can be useful to detect what type of
input that causes bad performance.

**Comment by hellux** [comment]
manage to separate each stage from the previous ones, so changed to new groups:

- block: only block parse (same)
- inline: only inline parse (exclude block parse from time)
- html: only html write (exclude block/inline, store events to vector before start time)
- full: perform full djot to html (roughly block+inline+html)

also added throughput, so easier to compare differently sized inputs

```
block/lorem1                    [727.82 MiB/s 730.06 MiB/s 732.82 MiB/s]
block/inline_autolink           [503.17 MiB/s 503.29 MiB/s 503.42 MiB/s]
block/block_ref_nested          [374.50 MiB/s 374.56 MiB/s 374.61 MiB/s]
block/block_ref_flat            [371.32 MiB/s 371.69 MiB/s 371.95 MiB/s]
block/inline_links_flat         [364.92 MiB/s 366.28 MiB/s 368.02 MiB/s]
block/inline_links_nested       [336.34 MiB/s 336.47 MiB/s 336.60 MiB/s]
block/inline_em_worst           [315.39 MiB/s 315.62 MiB/s 315.85 MiB/s]
block/readme                    [294.11 MiB/s 294.55 MiB/s 294.99 MiB/s]
block/inline_em_nested          [223.84 MiB/s 223.98 MiB/s 224.11 MiB/s]
block/inline_em_flat            [222.04 MiB/s 222.98 MiB/s 223.81 MiB/s]
block/block_bq_flat             [222.13 MiB/s 222.28 MiB/s 222.42 MiB/s]
block/inline_escape             [203.21 MiB/s 203.56 MiB/s 204.03 MiB/s]
block/block_hr                  [130.21 MiB/s 130.52 MiB/s 130.79 MiB/s]
block/inline_backticks          [105.96 MiB/s 106.04 MiB/s 106.14 MiB/s]
block/block_bq_nested           [105.59 MiB/s 105.70 MiB/s 105.82 MiB/s]
block/block_fences              [79.148 MiB/s 80.681 MiB/s 81.631 MiB/s]
block/block_code                [77.947 MiB/s 77.983 MiB/s 78.019 MiB/s]
block/block_list_flat           [57.841 MiB/s 57.868 MiB/s 57.891 MiB/s]
block/block_list_nested         [40.547 MiB/s 40.559 MiB/s 40.572 MiB/s]
block/block_heading             [31.043 MiB/s 31.091 MiB/s 31.132 MiB/s]

inline/block_code               [291.73 MiB/s 292.11 MiB/s 292.43 MiB/s]
inline/block_fences             [266.06 MiB/s 266.40 MiB/s 266.67 MiB/s]
inline/inline_autolink          [88.710 MiB/s 88.738 MiB/s 88.764 MiB/s]
inline/block_bq_nested          [80.042 MiB/s 80.077 MiB/s 80.110 MiB/s]
inline/readme                   [74.664 MiB/s 74.680 MiB/s 74.697 MiB/s]
inline/lorem1                   [72.201 MiB/s 72.213 MiB/s 72.225 MiB/s]
inline/inline_links_flat        [66.092 MiB/s 66.138 MiB/s 66.185 MiB/s]
inline/block_bq_flat            [60.723 MiB/s 60.731 MiB/s 60.738 MiB/s]
inline/block_ref_flat           [59.528 MiB/s 59.555 MiB/s 59.580 MiB/s]
inline/block_list_flat          [46.427 MiB/s 46.536 MiB/s 46.595 MiB/s]
inline/block_heading            [44.922 MiB/s 44.974 MiB/s 45.028 MiB/s]
inline/inline_em_worst          [41.350 MiB/s 41.362 MiB/s 41.375 MiB/s]
inline/inline_backticks         [41.263 MiB/s 41.276 MiB/s 41.288 MiB/s]
inline/block_list_nested        [41.525 MiB/s 41.538 MiB/s 41.555 MiB/s]
inline/block_hr                 [41.806 MiB/s 41.819 MiB/s 41.831 MiB/s]
inline/inline_em_nested         [37.152 MiB/s 37.165 MiB/s 37.178 MiB/s]
inline/inline_escape            [34.050 MiB/s 34.061 MiB/s 34.073 MiB/s]
inline/inline_em_flat           [34.851 MiB/s 34.865 MiB/s 34.878 MiB/s]
inline/block_ref_nested         [32.043 MiB/s 32.103 MiB/s 32.145 MiB/s]
inline/inline_links_nested      [31.976 MiB/s 31.984 MiB/s 31.993 MiB/s]

html/inline_links_nested        [113.49 Melem/s 113.70 Melem/s 113.86 Melem/s]
html/block_ref_nested           [110.62 Melem/s 110.68 Melem/s 110.74 Melem/s]
html/inline_escape              [104.28 Melem/s 104.66 Melem/s 105.00 Melem/s]
html/block_hr                   [104.75 Melem/s 104.79 Melem/s 104.82 Melem/s]
html/inline_em_worst            [101.48 Melem/s 101.82 Melem/s 102.17 Melem/s]
html/block_ref_flat             [81.529 Melem/s 81.682 Melem/s 81.811 Melem/s]
html/block_list_flat            [78.215 Melem/s 78.405 Melem/s 78.582 Melem/s]
html/block_list_nested          [74.812 Melem/s 74.866 Melem/s 74.914 Melem/s]
html/inline_em_flat             [69.958 Melem/s 69.994 Melem/s 70.030 Melem/s]
html/inline_em_nested           [66.749 Melem/s 66.878 Melem/s 67.012 Melem/s]
html/block_bq_flat              [59.821 Melem/s 59.855 Melem/s 59.885 Melem/s]
html/inline_links_flat          [57.415 Melem/s 57.840 Melem/s 58.233 Melem/s]
html/inline_backticks           [56.808 Melem/s 56.839 Melem/s 56.876 Melem/s]
html/block_bq_nested            [56.128 Melem/s 56.155 Melem/s 56.181 Melem/s]
html/block_fences               [46.688 Melem/s 46.768 Melem/s 46.866 Melem/s]
html/readme                     [43.009 Melem/s 43.140 Melem/s 43.235 Melem/s]
html/block_code                 [43.877 Melem/s 43.951 Melem/s 44.042 Melem/s]
html/lorem1                     [34.427 Melem/s 34.743 Melem/s 35.040 Melem/s]
html/inline_autolink            [32.271 Melem/s 32.321 Melem/s 32.379 Melem/s]
html/block_heading              [32.306 Melem/s 32.358 Melem/s 32.407 Melem/s]

full/inline_autolink            [66.808 MiB/s 66.858 MiB/s 66.906 MiB/s]
full/lorem1                     [60.328 MiB/s 60.349 MiB/s 60.370 MiB/s]
full/block_code                 [58.511 MiB/s 58.591 MiB/s 58.681 MiB/s]
full/block_fences               [56.438 MiB/s 56.529 MiB/s 56.592 MiB/s]
full/readme                     [52.771 MiB/s 52.786 MiB/s 52.800 MiB/s]
full/inline_links_flat          [48.384 MiB/s 48.397 MiB/s 48.411 MiB/s]
full/block_ref_flat             [44.456 MiB/s 44.471 MiB/s 44.484 MiB/s]
full/block_bq_nested            [42.015 MiB/s 42.026 MiB/s 42.036 MiB/s]
full/block_bq_flat              [42.455 MiB/s 42.536 MiB/s 42.608 MiB/s]
full/inline_em_worst            [31.878 MiB/s 31.915 MiB/s 31.959 MiB/s]
full/block_hr                   [29.308 MiB/s 29.326 MiB/s 29.346 MiB/s]
full/inline_em_nested           [27.298 MiB/s 27.314 MiB/s 27.326 MiB/s]
full/inline_links_nested        [26.357 MiB/s 26.376 MiB/s 26.393 MiB/s]
full/block_ref_nested           [26.686 MiB/s 26.701 MiB/s 26.717 MiB/s]
full/inline_escape              [25.558 MiB/s 25.564 MiB/s 25.571 MiB/s]
full/inline_backticks           [25.666 MiB/s 25.689 MiB/s 25.712 MiB/s]
full/inline_em_flat             [24.660 MiB/s 24.667 MiB/s 24.675 MiB/s]
full/block_list_flat            [23.261 MiB/s 23.266 MiB/s 23.271 MiB/s]
full/block_list_nested          [18.073 MiB/s 18.081 MiB/s 18.089 MiB/s]
full/block_heading              [15.806 MiB/s 15.810 MiB/s 15.814 MiB/s]
```

this gives some hints to what types of input are extra problematic for each stage

**Comment by hellux** [comment]
also added a concatenation of all inputs to get some kind of rough quick average:
```
block/all               time:   [85.454 µs 85.474 µs 85.491 µs]
                        thrpt:  [242.23 MiB/s 242.27 MiB/s 242.33 MiB/s]

inline/all              time:   [322.71 µs 322.80 µs 322.91 µs]
                        thrpt:  [64.130 MiB/s 64.151 MiB/s 64.170 MiB/s]

html/all                time:   [52.532 µs 52.614 µs 52.712 µs]
                        thrpt:  [55.016 Melem/s 55.119 Melem/s 55.204 Melem/s]

full/all                time:   [444.83 µs 444.90 µs 444.97 µs]
                        thrpt:  [46.538 MiB/s 46.545 MiB/s 46.553 MiB/s]
```

**Comment by kmaasrud** [comment]
Great stuff! This will make it easier to tackle any bottlenecks. Everything LGTM 👍

**Comment by hellux** [comment]
added another type of benchmark: iai. It measures not real-time performance but instead exact number of instructions and memory accesses, e.g:

```
full
  Instructions:             5782611 (No change)
  L1 Accesses:              8160187 (No change)
  L2 Accesses:                 4736 (No change)
  RAM Accesses:                3054 (No change)
  Estimated Cycles:         8290757 (No change)
```
it is also completely deterministic between runs, even between compilations it seems.

I needed to use the `deterministic` flag, though, it replaces hash maps with btrees. They have slightly worse performance but they have no randomness, allowing us to completely eliminate noise from these benchmarks.

**Comment by hellux** [comment]
added task to run benchmarks in ci, uploads benchmark results as an artifact (for 90 days I think)

**Pull request closed without merging**
