### PR TITLE
chore: add .gitignore files

### PR DESCRIPTION
**Pull request by not-my-profile**

### CODE REVIEW

**Comment by not-my-profile** [comment]
Sidenote: I think it's a bit unusual that the Makefile copies the binary into the top-level directory.

**Comment by hellux** [comment]
> Sidenote: I think it's a bit unusual that the Makefile copies the
> binary into the top-level directory.

I think it was mostly to have a convenient target that corresponds to
the actual file it creates and also make it easy to find. Probably not
very typical for Rust projects, though, since they are run mostly
through cargo anyway.

Is there a benefit to having multiple .gitignore files spread out
instead of placing everything in the root .gitignore? It seems easier to
read and edit if it is just a single file.

**Comment by not-my-profile** [comment]
Yeah defining the gitignores as close to the ignored files as possible helps with maintainability when moving dirs around or removing dirs, you're less likely to end up with outdated or leftover gitignore entries.

**Comment by hellux** [comment]
looks good, thanks!

**Pull request merged**
